### ISSUE TITLE
encoding not working on multiple node

### ISSUE THREAD

**Issue by x1wins** [x1wins/CW-OVP#3]
I got crash error when multiple node
worker can't find uploaded file that stored in local server
I have to change local file path to ```NFS``` or ```symbolic link``` or ```S3``` such as block storage for sharing between multiple server

```bash
19:12:07 job.1    | 2020-07-16T02:12:07.067Z pid=74563 tid=ov9pcqcsv class=EncodeWorker jid=2393fed14ccf25494ff38e53 INFO: start
19:12:07 job.1    | 2020-07-16T02:12:07.073Z pid=74563 tid=ov9pcqcsv class=EncodeWorker jid=2393fed14ccf25494ff38e53 elapsed=0.006 INFO: fail
19:12:07 job.1    | 2020-07-16T02:12:07.074Z pid=74563 tid=ov9pcqcsv WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"EncodeWorker","args":["#<Encode:0x00007fba94acb858>"],"jid":"2393fed14ccf25494ff38e53","created_at":1594845654.705516,"enqueued_at":1594865527.0652952,"error_message":"wrong number of arguments (given 1, expected 2)","error_class":"ArgumentError","failed_at":1594845654.7858062,"retry_count":8,"retried_at":1594865527.0069911},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"EncodeWorker\",\"args\":[\"#<Encode:0x00007fba94acb858>\"],\"jid\":\"2393fed14ccf25494ff38e53\",\"created_at\":1594845654.705516,\"enqueued_at\":1594865527.0652952,\"error_message\":\"wrong number of arguments (given 1, expected 2)\",\"error_class\":\"ArgumentError\",\"failed_at\":1594845654.7858062,\"retry_count\":8,\"retried_at\":1594865527.0069911}"}
19:12:07 job.1    | 2020-07-16T02:12:07.074Z pid=74563 tid=ov9pcqcsv WARN: ArgumentError: wrong number of arguments (given 1, expected 2)
19:12:07 job.1    | 2020-07-16T02:12:07.074Z pid=74563 tid=ov9pcqcsv WARN: /Users/rhee/project/CW-OVP/app/workers/encode_worker.rb:5:in `perform'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:196:in `execute_job'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:163:in `block in process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:111:in `local'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:14:in `block in call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:13:in `call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:257:in `stats'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:13:in `call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:78:in `global'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:124:in `block in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/logger.rb:10:in `with'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:33:in `prepare'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:123:in `dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:162:in `process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:78:in `process_one'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:68:in `run'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:15:in `watchdog'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
19:12:07 job.1    | 2020-07-16T02:12:07.104Z pid=74563 tid=ov9pctlhf class=EncodeWorker jid=fb8161c1008dcb1d7cf638e4 INFO: start
19:12:07 job.1    | 2020-07-16T02:12:07.109Z pid=74563 tid=ov9pctlhf class=EncodeWorker jid=fb8161c1008dcb1d7cf638e4 elapsed=0.005 INFO: fail
19:12:07 job.1    | 2020-07-16T02:12:07.109Z pid=74563 tid=ov9pctlhf WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","class":"EncodeWorker","args":["#<Encode:0x00007fba8f40f550>"],"jid":"fb8161c1008dcb1d7cf638e4","created_at":1594845983.1612182,"enqueued_at":1594865527.1025221,"error_message":"wrong number of arguments (given 1, expected 2)","error_class":"ArgumentError","failed_at":1594845983.2229362,"retry_count":8,"retried_at":1594865527.0920582},"jobstr":"{\"retry\":true,\"queue\":\"default\",\"class\":\"EncodeWorker\",\"args\":[\"#<Encode:0x00007fba8f40f550>\"],\"jid\":\"fb8161c1008dcb1d7cf638e4\",\"created_at\":1594845983.1612182,\"enqueued_at\":1594865527.1025221,\"error_message\":\"wrong number of arguments (given 1, expected 2)\",\"error_class\":\"ArgumentError\",\"failed_at\":1594845983.2229362,\"retry_count\":8,\"retried_at\":1594865527.0920582}"}
19:12:07 job.1    | 2020-07-16T02:12:07.109Z pid=74563 tid=ov9pctlhf WARN: ArgumentError: wrong number of arguments (given 1, expected 2)
19:12:07 job.1    | 2020-07-16T02:12:07.109Z pid=74563 tid=ov9pctlhf WARN: /Users/rhee/project/CW-OVP/app/workers/encode_worker.rb:5:in `perform'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:196:in `execute_job'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:163:in `block in process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:111:in `local'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:14:in `block in call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:13:in `call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:257:in `stats'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:13:in `call'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:78:in `global'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:124:in `block in dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/logger.rb:10:in `with'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:33:in `prepare'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:123:in `dispatch'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:162:in `process'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:78:in `process_one'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:68:in `run'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:15:in `watchdog'
19:12:07 job.1    | /Users/rhee/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by x1wins** [comment]
this is same issue with https://github.com/x1wins/CW-OVP/issues/22
