### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly

### ISSUE THREAD

**Issue by x1wins** [x1wins/CW-OVP#38]
```
2020-11-13T04:45:45.126Z pid=1 tid=grcr7pbzl class=EncodeWorker jid=820388786b0e5ae0b6041902 elapsed=1951.914 INFO: fail
2020-11-13T04:45:45.126Z pid=1 tid=grcr7pbzl WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"default","backtrace":true,"class":"EncodeWorker","args":[71],"jid":"820388786b0e5ae0b6041902","created_at":1605240793.208652,"enqueued_at":1605240793.208673},"jobstr":"{\"retry\":false,\"queue\":\"default\",\"backtrace\":true,\"class\":\"EncodeWorker\",\"args\":[71],\"jid\":\"820388786b0e5ae0b6041902\",\"created_at\":1605240793.208652,\"enqueued_at\":1605240793.208673}"}
2020-11-13T04:45:45.126Z pid=1 tid=grcr7pbzl WARN: ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

2020-11-13T04:45:45.126Z pid=1 tid=grcr7pbzl WARN: /usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `exec'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:92:in `block (2 levels) in execute'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:91:in `block in execute'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:90:in `execute'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:150:in `begin_db_transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `materialize!'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:246:in `block (2 levels) in materialize_transactions'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:246:in `each'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:246:in `block in materialize_transactions'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:243:in `materialize_transactions'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:288:in `materialize_transactions'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:666:in `exec_no_cache'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:656:in `execute_and_clear'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:111:in `exec_delete'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:174:in `update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:385:in `_update_record'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:896:in `_update_row'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/locking/optimistic.rb:79:in `_update_row'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:918:in `_update_record'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/attribute_methods/dirty.rb:205:in `_update_record'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/callbacks.rb:335:in `block in _update_record'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:825:in `_run_update_callbacks'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/callbacks.rb:335:in `_update_record'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/timestamp.rb:123:in `_update_record'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:905:in `create_or_update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/callbacks.rb:327:in `block in create_or_update'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:825:in `_run_save_callbacks'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/callbacks.rb:327:in `create_or_update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/timestamp.rb:128:in `create_or_update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:470:in `save'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/validations.rb:47:in `save'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:314:in `block in save'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:314:in `save'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/suppressor.rb:44:in `save'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:621:in `block in update'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/usr/local/bundle/ruby/2.6.0/gems/activerecord-6.0.3.2/lib/active_record/persistence.rb:619:in `update'
/myapp/app/workers/encode_worker.rb:66:in `block in perform'
/usr/local/bundle/ruby/2.6.0/gems/activestorage-6.0.3.2/lib/active_storage/downloader.rb:15:in `block in open'
/usr/local/bundle/ruby/2.6.0/gems/activestorage-6.0.3.2/lib/active_storage/downloader.rb:24:in `open_tempfile'
/usr/local/bundle/ruby/2.6.0/gems/activestorage-6.0.3.2/lib/active_storage/downloader.rb:12:in `open'
/usr/local/bundle/ruby/2.6.0/gems/activestorage-6.0.3.2/lib/active_storage/service.rb:86:in `open'
/usr/local/bundle/ruby/2.6.0/gems/activestorage-6.0.3.2/app/models/active_storage/blob.rb:219:in `open'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/module/delegation.rb:304:in `public_send'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/module/delegation.rb:304:in `method_missing'
/myapp/app/workers/encode_worker.rb:9:in `perform'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:196:in `execute_job'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:163:in `block in process'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:111:in `local'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:14:in `block in call'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/usr/local/bundle/ruby/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/rails.rb:13:in `call'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:257:in `stats'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_retry.rb:78:in `global'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:124:in `block in dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/logger.rb:10:in `with'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/job_logger.rb:33:in `prepare'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:123:in `dispatch'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:162:in `process'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:78:in `process_one'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/processor.rb:68:in `run'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:15:in `watchdog'
/usr/local/bundle/ruby/2.6.0/gems/sidekiq-6.1.0/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by x1wins** [comment]
```
ActiveRecord::Base.connection_pool.release_connection
ActiveRecord::Base.connection_pool.with_connection do
         # code of save, update
end
```
